### ISSUE TITLE
RangeError An error occurred. Invalid time value

### ISSUE THREAD

**Issue by neo-art** [themefisher/bookworm-light-astro#15]
Hello,

I am trying to add Keystatic to my existing Bookworm Astro project but I got the following error message:
RangeError
An error occurred.
Invalid time value
date-fns/format.mjs:352:11

<img width="1296" alt="Screenshot 2024-04-25 at 22 27 11" src="https://github.com/themefisher/bookworm-light-astro/assets/5845802/634263c6-acfb-4262-abe8-1a3d1b68d189">

Any idea what can cause the issue?

**Comment by tfsomrat** [comment]
hey @neo-art, can you share your repository?

**Comment by neo-art** [comment]
> hey @neo-art, can you share your repository?

Sure thing:
[https://github.com/themefisher/bookworm-light-astro](https://github.com/themefisher/bookworm-light-astro)

**Comment by tfsomrat** [comment]
I was asking for your repository, not the original one.

**Comment by neo-art** [comment]
Sorry copied wrong url:

[https://github.com/neo-art/bookworm-light-astro](https://github.com/neo-art/bookworm-light-astro)

**Comment by tfsomrat** [comment]
Hey @neo-art, we didn't give support after customizing or added some other packages. we only provide support if the theme has any built-in issue. if you need customization service, you can contact us here: https://themefisher.com/custom-development
