### ISSUE TITLE
Post preview / excerpt does not render as markdown

### ISSUE THREAD

**Issue by selipso** [themefisher/bookworm-light-astro#16]
The problem stems from the following line in `src/layouts/Posts.astro`: `post.body?.slice(0, Number(i === 0 && fluid != false ? summary_length * 2 : summary_length))`

This is plain markdown that is shown directly, so if there is any kind of syntax like a heading or link early on in the post, it will look ugly in the preview. My suggestion is to use a generic mardown parser that is compatible with astro like [astro-remote](https://github.com/natemoo-re/astro-remote?tab=readme-ov-file) to parse the content and show the post preview properly in the list of Posts.

I can submit a PR if you think this is a good approach?

**Comment by tfsomrat** [comment]
Hey @selipso, we fixed that issue. thanks
