### ISSUE TITLE
Request for adding mailchimp email subscription box in footer and sample contact form response

### ISSUE THREAD

**Issue by eric-stanley** [themefisher/bookworm-light-astro#3]
Would be good if we have a subscription box in footer for mailchimp along with adding sample response in contact form by adding dummy function to extract values from contact form and then showing the values in alert followed by success response and display response in the same page

**Comment by tfsomrat** [comment]
Hey @eric-stanley 

thanks for choosing our theme. we don't currently have any plans for this. but if you want any feature improvement or theme customization, then you can contact us here https://themefisher.com/custom-development
