### ISSUE TITLE
Please help me how i add Google adsense code in Blog post

### ISSUE THREAD

**Issue by Nexus-Gits** [themefisher/bookworm-light-astro#5]
Please help me how i add Google adsense code in Blog post. Any of the ads like Google Adsense Auto ads or Custom ads.
Please tell me if anyone know how to add the Google adse code in Astro site.

**Comment by tfsomrat** [comment]
Hi, you can use this npm module to achieve your goal https://www.npmjs.com/package/react-adsense

thanks
