### ISSUE TITLE
Front Matter "draft" tag may not be working

### ISSUE THREAD

**Issue by taokawarai** [themefisher/bookworm-light-astro#6]
Hi

I started to use this great template!
Now, I noticed that frontmatter `draft` tag mey not be working. I confirmed that all posts displayed whether `draft` tag is true or false. 

I got Removing draft posts processes written in `src/lib/contentParser.astro`. Should I use some method? I new to Astro, so I appliciate to teaching me how to solve this.

**Comment by tfsomrat** [comment]
hey @taokawarai 

It should work now. take a look
